### ISSUE TITLE
Binding C APIs with variable-length structs and UTF-16

### ISSUE THREAD

**Issue by kwas** [fasterthanlime/feedback#49]
I found something wrong on this page:

https://fasterthanli.me/series/making-our-own-ping/part-8#position=69.6

Here's what it is:

Code as it written doesn't work with latest version (0.5.0) of custom_debug_derive.
To make it work I added `use custom_debug_derive::Debug;` and then replace `#[derive(CustomDebug)]` with `#[derive(Debug)]`

`use custom_debug_derive::*;` won't work because of ambiguity:
```
error[E0659]: `Debug` is ambiguous
   --> src\netinfo.rs:31:10
    |
31  | #[derive(Debug)]
    |          ^^^^^ ambiguous name
    |
    = note: ambiguous because of a conflict between a name from a glob import and an outer scope during import or macro resolution
note: `Debug` could refer to the derive macro imported here
   --> src\netinfo.rs:4:5
    |
4   | use custom_debug_derive::*;
    |     ^^^^^^^^^^^^^^^^^^^^^^
    = help: consider adding an explicit import of `Debug` to disambiguate
    = help: or use `self::Debug` to refer to this derive macro unambiguously
note: `Debug` could also refer to the derive macro defined here
   --> C:\Users\kwas\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\std\src\prelude\mod.rs:129:13
    |
129 |     pub use super::v1::*;
    |             ^^^^^^^^^^^^
```

**Comment by fasterthanlime** [comment]
Fixed, thanks!
